[2024-04-13 23:12:00] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:05] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:10] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:15] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:20] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:25] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:25] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 905d54621bd8d9e7 [::1]:34868 failed checkpoint posthandshake: Connected to self
[2024-04-13 23:12:25] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 905d54621bd8d9e7 [::1]:20136 failed checkpoint posthandshake: Connected to self
[2024-04-13 23:12:30] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:35] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:40] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:45] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:50] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:55] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 23:12:57] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 905d54621bd8d9e7 [::1]:56716 failed checkpoint posthandshake: Connected to self
[2024-04-13 23:12:57] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 905d54621bd8d9e7 [::1]:20136 failed checkpoint posthandshake: Connected to self
