[2024-04-13 15:43:06] [warning] server.go:553 p3Chain/p2p/server.(*Server).encHandshakeChecks 进行加密handshake: 节点已经与本机建立了连接

[2024-04-13 15:43:06] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 2680fb919c17c10a [::1]:20132 failed checkpoint posthandshake: Already connected
[2024-04-13 15:43:27] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:27] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 0ff6e4ca1d612ede [::1]:52550 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:27] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 0ff6e4ca1d612ede [::1]:20130 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:32] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:32] [error] orderServer.go:593 p3Chain/core/blockOrdering.(*BlockOrderServer).simpleInit [Block Ordering] fail in simpleInit, no enough state messages collected!

[2024-04-13 15:43:37] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:38] [error] orderServer.go:593 p3Chain/core/blockOrdering.(*BlockOrderServer).simpleInit [Block Ordering] fail in simpleInit, no enough state messages collected!

[2024-04-13 15:43:42] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:43] [error] orderServer.go:593 p3Chain/core/blockOrdering.(*BlockOrderServer).simpleInit [Block Ordering] fail in simpleInit, no enough state messages collected!

[2024-04-13 15:43:47] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:52] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:57] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:57] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 0ff6e4ca1d612ede [::1]:42632 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:57] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 0ff6e4ca1d612ede [::1]:20130 failed checkpoint posthandshake: Connected to self
