[2024-04-13 16:46:00] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:05] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:05] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 21c561939067af2d [::1]:52192 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:46:05] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 21c561939067af2d [::1]:20133 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:46:10] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:15] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:20] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:25] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:30] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:35] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:37] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 21c561939067af2d [::1]:53776 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:46:37] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 21c561939067af2d [::1]:20133 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:46:40] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:45] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:50] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:46:55] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
